/*
 * Copyright 2017 Outfox, Inc.
 * Copyright 2026 LL Data ApS
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dk.lldata.typescriptpoet.test;

import dk.lldata.typescriptpoet.ClassSpec;
import dk.lldata.typescriptpoet.CodeBlock;
import dk.lldata.typescriptpoet.DecoratorSpec;
import dk.lldata.typescriptpoet.EnumSpec;
import dk.lldata.typescriptpoet.ExportSpec;
import dk.lldata.typescriptpoet.FileSpec;
import dk.lldata.typescriptpoet.FunctionSpec;
import dk.lldata.typescriptpoet.InterfaceSpec;
import dk.lldata.typescriptpoet.Modifier;
import dk.lldata.typescriptpoet.ModuleSpec;
import dk.lldata.typescriptpoet.ObjectLiteral;
import dk.lldata.typescriptpoet.ParameterSpec;
import dk.lldata.typescriptpoet.PropertySpec;
import dk.lldata.typescriptpoet.SymbolSpec;
import dk.lldata.typescriptpoet.TypeAliasSpec;
import dk.lldata.typescriptpoet.TypeName;

import java.io.IOException;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * {@link KitchenSink}, written in Java.
 *
 * <p>The library calls itself a Kotlin <em>and Java</em> API, and this is the claim tested at
 * full size: every construct the library can emit, reached without Kotlin. {@code
 * KitchenSinkJavaTest} asserts it emits the same file as the Kotlin version, byte for byte.
 *
 * <p>Where this is more awkward than the Kotlin it mirrors, that is the finding rather than a
 * flaw in the port -- see the notes inline.
 */
final class KitchenSinkJava {

  private KitchenSinkJava() {
  }

  @SuppressWarnings("MethodLength")
  static FileSpec spec() {
    TypeName t = TypeName.typeVariable("T");
    TypeName k = TypeName.typeVariable("K");
    TypeName person = TypeName.implicit("Person");

    TypeName engine = TypeName.namedImport("Engine", "./engine");
    TypeName logger = TypeName.defaultImport("Logger", "./logger");
    TypeName options = TypeName.namedImport("Options", "./options", true);
    SymbolSpec sealedDecorator = SymbolSpec.importsName("sealed", "./decorators");
    SymbolSpec loggedDecorator = SymbolSpec.importsName("logged", "./decorators");

    FileSpec.Builder file = FileSpec.builder("kitchen-sink")
        .addComment("Generated by TypeScriptPoet. Do not edit.\n");

    // ---- Imports ----
    file.addCode(CodeBlock.of("%Q;\n", SymbolSpec.sideEffect("polyfillLoaded", "./polyfill")));

    // ---- Interfaces ----
    file.addInterface(
        InterfaceSpec.builder("Person")
            .addModifiers(Modifier.EXPORT)
            .addTSDoc("A person, as described by the source metadata.\n")
            .addProperty("name", TypeName.STRING)
            .addProperty("age", TypeName.NUMBER, true)
            .addProperty(
                PropertySpec.builder("id", TypeName.STRING)
                    .addModifiers(Modifier.READONLY)
                    .build())
            .build());

    file.addInterface(
        InterfaceSpec.builder("Callable")
            .addModifiers(Modifier.EXPORT)
            .callable(
                FunctionSpec.callableBuilder()
                    .addModifiers(Modifier.ABSTRACT)
                    .addParameter("value", TypeName.STRING)
                    .returns(TypeName.NUMBER)
                    .build())
            .addIndexable(
                FunctionSpec.indexableBuilder()
                    .addModifiers(Modifier.ABSTRACT)
                    .addParameter("key", TypeName.STRING)
                    .returns(TypeName.implicit("unknown"))
                    .build())
            .build());

    file.addInterface(
        InterfaceSpec.builder("Identified")
            .addModifiers(Modifier.EXPORT)
            .addProperty(
                PropertySpec.builder("id", TypeName.STRING)
                    .addModifiers(Modifier.READONLY)
                    .build())
            .build());

    file.addInterface(
        InterfaceSpec.builder("Labelled")
            .addModifiers(Modifier.EXPORT)
            .addSuperInterface(TypeName.implicit("Identified"))
            .addProperty("label", TypeName.STRING)
            .build());

    // ---- Type aliases ----
    file.addTypeAlias(TypeAliasSpec.builder("PersonKey", TypeName.keyOf(person)).build());
    file.addTypeAlias(
        TypeAliasSpec.builder("PersonName", TypeName.indexedAccess(person, TypeName.implicit("\"name\""))).build());
    file.addTypeAlias(
        TypeAliasSpec.builder("Names", TypeName.readOnly(TypeName.arrayShorthandType(TypeName.STRING))).build());
    file.addTypeAlias(TypeAliasSpec.builder("Engines", TypeName.arrayType(engine)).build());
    file.addTypeAlias(
        TypeAliasSpec.builder("Registry", TypeName.mapType(TypeName.STRING, TypeName.NUMBER)).build());
    file.addTypeAlias(TypeAliasSpec.builder("Unique", TypeName.setType(TypeName.STRING)).build());
    file.addTypeAlias(
        TypeAliasSpec.builder(
                "Coordinates",
                TypeName.readOnly(
                    TypeName.tupleType(
                        List.of(
                            // Java has no named arguments, so every defaulted parameter has to be
                            // written out: `label = "x"` becomes three more positional values.
                            TypeName.tupleMember(TypeName.NUMBER, "x", false, false),
                            TypeName.tupleMember(TypeName.NUMBER, "y", true, false)))))
            .build());
    file.addTypeAlias(
        TypeAliasSpec.builder(
                "Rest",
                TypeName.tupleType(
                    List.of(
                        TypeName.tupleMember(TypeName.STRING, null, false, false),
                        TypeName.tupleMember(
                            TypeName.arrayShorthandType(TypeName.NUMBER), "rest", false, true))))
            .build());
    file.addTypeAlias(
        TypeAliasSpec.builder("Choice", TypeName.unionType(TypeName.STRING, TypeName.NUMBER, TypeName.NULL)).build());
    file.addTypeAlias(
        TypeAliasSpec.builder(
                "LocationLabelKind",
                TypeName.unionType(
                    TypeName.literal("MARKETPLACE"),
                    TypeName.literal("DISTRICT"),
                    TypeName.literal("COUNTRY"),
                    TypeName.literal("UNKNOWN")))
            .addModifiers(Modifier.EXPORT)
            .build());

    // A range-map-toArray in Kotlin; a loop and an array in Java.
    TypeName[] verbose = new TypeName[4];
    for (int i = 1; i <= 4; i++) {
      verbose[i - 1] = TypeName.literal("PARTITION_KEY_CANDIDATE_" + i);
    }
    file.addTypeAlias(TypeAliasSpec.builder("Verbose", TypeName.unionType(verbose)).build());

    file.addTypeAlias(TypeAliasSpec.builder("Both", TypeName.intersectionType(person, options)).build());
    file.addTypeAlias(
        TypeAliasSpec.builder(
                "Anon",
                TypeName.anonymousType(
                    List.of(
                        new TypeName.Anonymous.Member("label", TypeName.STRING, false),
                        new TypeName.Anonymous.Member("hint", TypeName.STRING, true))))
            .build());
    file.addTypeAlias(
        TypeAliasSpec.builder(
                "MixedArray", TypeName.arrayShorthandType(TypeName.unionType(TypeName.STRING, TypeName.NUMBER)))
            .build());
    file.addTypeAlias(
        TypeAliasSpec.builder("KeysOfEither", TypeName.keyOf(TypeName.unionType(person, options))).build());

    // Kotlin writes `"event" to TypeName.STRING`; Java needs the Map overload, and a
    // LinkedHashMap rather than Map.of because parameter order has to survive.
    Map<String, TypeName> eventParam = new LinkedHashMap<>();
    eventParam.put("event", TypeName.STRING);
    file.addTypeAlias(
        TypeAliasSpec.builder("Handler", TypeName.lambda(eventParam, TypeName.VOID)).build());

    Map<String, TypeName> identityParams = new LinkedHashMap<>();
    identityParams.put("value", TypeName.typeVariable("V"));
    file.addTypeAlias(
        TypeAliasSpec.builder(
                "Identity",
                TypeName.genericLambda(
                    List.of(TypeName.typeVariable("V")), identityParams, TypeName.typeVariable("V")))
            .build());
    file.addTypeAlias(
        TypeAliasSpec.builder("EngineFactory", TypeName.constructorType(Map.of(), engine, List.of(), false)).build());
    file.addTypeAlias(
        TypeAliasSpec.builder("AbstractEngineFactory", TypeName.constructorType(Map.of(), engine, List.of(), true)).build());
    file.addTypeAlias(
        TypeAliasSpec.builder("Bounded", TypeName.lambda(Map.of(), TypeName.typeVariable("B")))
            .addTypeVariable(TypeName.typeVariable("B", TypeName.bound(person)))
            .build());
    file.addTypeAlias(
        TypeAliasSpec.builder("Producer", TypeName.lambda(Map.of(), TypeName.typeVariable("O")))
            .addTypeVariable(
                TypeName.typeVariable("O", TypeName.TypeVariable.Variance.OUT, false, List.of()))
            .build());
    file.addTypeAlias(
        TypeAliasSpec.builder(
                "Unwrap",
                TypeName.conditionalType(
                    t,
                    TypeName.arrayShorthandType(TypeName.infer("U")),
                    TypeName.typeVariable("U"),
                    TypeName.NEVER))
            .addTypeVariable((TypeName.TypeVariable) t)
            .build());
    file.addTypeAlias(
        TypeAliasSpec.builder(
                "Mutable",
                TypeName.mappedType(
                    "K",
                    TypeName.keyOf(t),
                    TypeName.indexedAccess(t, k),
                    null,
                    TypeName.Mapped.Change.REMOVE,
                    TypeName.Mapped.Change.ADD))
            .addTypeVariable((TypeName.TypeVariable) t)
            .build());
    file.addTypeAlias(
        TypeAliasSpec.builder(
                "Getters",
                TypeName.mappedType(
                    "K",
                    TypeName.keyOf(t),
                    TypeName.indexedAccess(t, k),
                    TypeName.templateLiteralType(
                        "get",
                        TypeName.parameterizedType(
                            TypeName.implicit("Capitalize"),
                            TypeName.parameterizedType(TypeName.implicit("Extract"), k, TypeName.STRING))),
                    null,
                    null))
            .addTypeVariable((TypeName.TypeVariable) t)
            .build());
    file.addTypeAlias(TypeAliasSpec.builder("TypeOfEngine", TypeName.typeOf((TypeName.Standard) engine)).build());
    file.addTypeAlias(
        TypeAliasSpec.builder("Lookup", TypeName.recordType(TypeName.STRING, TypeName.NUMBER)).build());

    Map<String, TypeName> constrainedParams = new LinkedHashMap<>();
    constrainedParams.put("value", TypeName.typeVariable("C"));
    constrainedParams.put("key", TypeName.typeVariable("P"));
    file.addTypeAlias(
        TypeAliasSpec.builder(
                "Constrained", TypeName.lambda(constrainedParams, TypeName.typeVariable("W")))
            .addTypeVariable(
                TypeName.typeVariable(
                    "C", TypeName.unionBound(TypeName.STRING, false), TypeName.unionBound(TypeName.NUMBER, false)))
            .addTypeVariable(TypeName.typeVariable("P", TypeName.unionBound(person, true)))
            .addTypeVariable(
                TypeName.typeVariable("W", TypeName.bound(person), TypeName.intersectBound(options, false)))
            .build());

    // ---- Enums ----
    file.addEnum(
        EnumSpec.builder("Direction")
            .addModifiers(Modifier.EXPORT)
            .addConstant("Up", CodeBlock.of("%S", "UP"))
            .addConstant("Down", CodeBlock.of("%S", "DOWN"))
            .build());
    file.addEnum(
        EnumSpec.builder("Flags")
            .addModifiers(Modifier.CONST)
            .addConstant("None", CodeBlock.of("0"))
            .addConstant("All", CodeBlock.of("1 << 2"))
            .build());

    // ---- Functions ----
    file.addFunction(
        FunctionSpec.builder("isPerson")
            .addModifiers(Modifier.EXPORT)
            .addTSDoc("Narrows an unknown value to %L.\n", "Person")
            .addParameter("value", TypeName.implicit("unknown"))
            .returnsIs("value", person)
            .addStatement("return typeof value === \"object\" && value !== null && \"name\" in value")
            .build());
    file.addFunction(
        FunctionSpec.builder("assertPerson")
            .addParameter("value", TypeName.implicit("unknown"))
            .returnsAsserts("value", person)
            .addStatement("if (!isPerson(value)) throw new Error(\"not a person\")")
            .build());
    file.addFunction(
        FunctionSpec.builder("assertReady")
            .addParameter("value", TypeName.implicit("unknown"))
            .returnsAsserts("value")
            .addStatement("if (!value) throw new Error(\"not ready\")")
            .build());
    file.addFunction(
        FunctionSpec.builder("pick")
            .addTypeVariable(TypeName.typeVariable("C", null, true, List.of()))
            .addParameter("value", TypeName.typeVariable("C"))
            .returns(TypeName.typeVariable("C"))
            .addStatement("return value")
            .build());
    file.addFunction(
        FunctionSpec.builder("describe")
            .thisParameter(person)
            .returns(TypeName.STRING)
            .addStatement("return this.name")
            .build());
    file.addFunction(
        FunctionSpec.builder("load")
            .addModifiers(Modifier.ASYNC)
            .returns(TypeName.parameterizedType(TypeName.PROMISE, TypeName.STRING))
            .addStatement("return \"loaded\"")
            .build());
    file.addFunction(
        FunctionSpec.builder("counter")
            .generator()
            .returns(TypeName.parameterizedType(TypeName.GENERATOR, TypeName.NUMBER))
            .addStatement("yield 1")
            .build());
    file.addFunction(
        FunctionSpec.builder("stream")
            .addModifiers(Modifier.ASYNC)
            .generator()
            .returns(TypeName.parameterizedType(TypeName.implicit("AsyncGenerator"), TypeName.NUMBER))
            .addStatement("yield 1")
            .build());
    file.addFunction(
        FunctionSpec.builder("greet")
            .addParameter(
                ParameterSpec.builder("greeting", TypeName.STRING)
                    .defaultValue("%S", "hello")
                    .build())
            .addParameter("name", TypeName.STRING, true)
            .restParameter("extras", TypeName.arrayShorthandType(TypeName.STRING))
            .returns(TypeName.STRING)
            .addStatement("return [greeting, name, ...extras].join(\" \")")
            .build());
    file.addFunction(
        FunctionSpec.builder("configure")
            .addParameter(
                ParameterSpec.builder("options", options)
                    .destructure(ParameterSpec.objectPattern(ParameterSpec.binding("verbose", "loud")))
                    .build())
            .returns(TypeName.BOOLEAN)
            .addStatement("return loud")
            .build());
    file.addFunction(
        FunctionSpec.builder("swap")
            .addParameter(
                ParameterSpec.builder("pair", TypeName.tupleType(TypeName.STRING, TypeName.STRING))
                    .destructure(ParameterSpec.arrayPattern("first", "second"))
                    .build())
            .returns(TypeName.tupleType(TypeName.STRING, TypeName.STRING))
            .addStatement("return [second, first]")
            .build());
    file.addFunction(
        FunctionSpec.builder("useUtils")
            .returns(TypeName.STRING)
            .addStatement("return %Q.identity(\"x\")", SymbolSpec.importsAll("utils", "./utils"))
            .build());

    List<FunctionSpec> overloads =
        FunctionSpec.overloads(
            List.of(
                FunctionSpec.builder("parse").addParameter("value", TypeName.STRING).returns(TypeName.STRING).build(),
                FunctionSpec.builder("parse").addParameter("value", TypeName.NUMBER).returns(TypeName.NUMBER).build()),
            FunctionSpec.builder("parse")
                .addParameter("value", TypeName.unionType(TypeName.STRING, TypeName.NUMBER))
                .returns(TypeName.unionType(TypeName.STRING, TypeName.NUMBER))
                .addStatement("return value")
                .build());
    for (FunctionSpec overload : overloads) {
      file.addFunction(overload);
    }

    file.addFunction(
        FunctionSpec.builder("classify")
            .addParameter("value", TypeName.NUMBER)
            .returns(TypeName.STRING)
            .beginControlFlow("if (value > 0)")
            .addStatement("return %S", "positive")
            .nextControlFlow("else if (value < 0)")
            .addStatement("return %S", "negative")
            .nextControlFlow("else")
            .addStatement("return %S", "zero")
            .endControlFlow()
            .build());

    file.addFunction(
        FunctionSpec.builder("boostEngine")
            .addParameter("engine", engine)
            .addStatement("engine.%Q()", SymbolSpec.augmented("boost", "./engine-boost", "Engine"))
            .build());

    // ---- Object literals ----
    ObjectLiteral node =
        CodeBlock.objectLiteral()
            .addProperty("kind", "%S", "node")
            .addShorthand("path")
            .addGetter("depth", "return path.split(%S).length", "/")
            .addProperty(
                "send",
                FunctionSpec.builder("send")
                    .arrow()
                    .addParameter("message", TypeName.STRING)
                    .returns(TypeName.VOID)
                    .addStatement("console.log(message)")
                    .build())
            .build();
    file.addFunction(
        FunctionSpec.builder("node")
            .addModifiers(Modifier.EXPORT)
            .addParameter("path", TypeName.STRING)
            .addStatement("return %L", node)
            .build());

    // ---- Call expressions ----
    file.addFunction(
        FunctionSpec.builder("loadDeviceConfiguration")
            .addModifiers(Modifier.EXPORT)
            .addParameter("path", TypeName.STRING)
            .addParameter("config", TypeName.namedImport("RequestConfig", "./fetch-resource"))
            .returns(TypeName.promiseType(TypeName.implicit("Widget")))
            .addStatement(
                "return %L",
                CodeBlock.call(TypeName.namedImport("fetchResource", "./fetch-resource"))
                    .addTypeArgument(TypeName.implicit("Widget"))
                    .addArgument(
                        CodeBlock.objectLiteral()
                            .addProperty("method", "%S", "POST")
                            .addShorthand("path")
                            .addProperty("retries", "%L", 3)
                            .build())
                    .addArgument("config")
                    .addArgument("undefined")
                    .build())
            .build());

    file.addFunction(
        FunctionSpec.builder("ping")
            .addStatement("return %L", CodeBlock.call("fetch").addArgument("%S", "/ping").build())
            .build());

    file.addFunction(
        FunctionSpec.builder("emptyIndex")
            .returns(TypeName.mapType(TypeName.STRING, TypeName.NUMBER))
            .addStatement(
                "return %L",
                CodeBlock.newInstance(TypeName.mapType(TypeName.STRING, TypeName.NUMBER)).build())
            .build());

    // ---- Concise arrow bodies ----
    file.addFunction(
        FunctionSpec.builder("doubler")
            .addModifiers(Modifier.EXPORT)
            .returns(TypeName.lambda(Map.of("value", TypeName.NUMBER), TypeName.NUMBER))
            .addStatement(
                "return %L",
                FunctionSpec.builder("double")
                    .arrow()
                    .addParameter("value", TypeName.NUMBER)
                    .expressionBody("value * 2")
                    .build())
            .build());

    file.addFunction(
        FunctionSpec.builder("wrap")
            .addModifiers(Modifier.EXPORT)
            .addStatement(
                "return %L",
                FunctionSpec.builder("wrapOne")
                    .arrow()
                    .addParameter("value", TypeName.NUMBER)
                    .expressionBody(
                        CodeBlock.of(
                            "%L", CodeBlock.objectLiteral().addShorthand("value").build()))
                    .build())
            .build());

    // ---- Inline object types ----
    file.addFunction(
        FunctionSpec.builder("listWidgets")
            .addModifiers(Modifier.EXPORT)
            .addParameter(
                ParameterSpec.builder(
                        "args",
                        TypeName.anonymousType(
                            List.of(
                                TypeName.anonymousMember(
                                    "limit",
                                    TypeName.NUMBER,
                                    true,
                                    CodeBlock.of("Server default: %L.\n", 20)),
                                TypeName.anonymousMember("cursor", TypeName.STRING, true),
                                TypeName.anonymousMember(
                                    "includeArchived", TypeName.BOOLEAN, true))),
                        true)
                    .build())
            .returns(
                TypeName.promiseType(TypeName.arrayShorthandType(TypeName.implicit("unknown"))))
            .addStatement(
                "return %L",
                CodeBlock.call(TypeName.namedImport("queryWidgets", "./fetch-resource"))
                    .addArgument("args")
                    .build())
            .build());

    // ---- Classes ----
    file.addClass(
        ClassSpec.builder("Base")
            .addModifiers(Modifier.EXPORT, Modifier.ABSTRACT)
            .addTypeVariable(TypeName.typeVariable("S", TypeName.bound(TypeName.STRING)))
            .addFunction(
                FunctionSpec.builder("greet")
                    .addModifiers(Modifier.PUBLIC)
                    .returns(TypeName.STRING)
                    .addStatement("return \"hi\"")
                    .build())
            .addFunction(
                FunctionSpec.builder("describe")
                    .addModifiers(Modifier.PROTECTED, Modifier.ABSTRACT)
                    .returns(TypeName.STRING)
                    .build())
            .build());

    Map<String, TypeName> onEventParam = new LinkedHashMap<>();
    onEventParam.put("event", TypeName.STRING);
    file.addClass(
        ClassSpec.builder("Widget")
            .addModifiers(Modifier.EXPORT)
            .addTSDoc("The widget the generator produces.\n")
            .addDecorator(DecoratorSpec.builder(sealedDecorator).build())
            .superClass(TypeName.parameterizedType(TypeName.implicit("Base"), TypeName.STRING))
            .addMixin(TypeName.implicit("Identified"))
            .addProperty(PropertySpec.builder("#secret", TypeName.STRING).initializer("%S", "s").build())
            .addProperty(
                PropertySpec.builder("later", TypeName.STRING)
                    .definiteAssignment()
                    .addDecorator(DecoratorSpec.builder(loggedDecorator).asFactory().build())
                    .build())
            .addProperty(
                PropertySpec.builder("count", TypeName.NUMBER)
                    .addModifiers(Modifier.ACCESSOR)
                    .initializer("0")
                    .build())
            .addProperty(
                PropertySpec.builder("registry", TypeName.mapType(TypeName.STRING, TypeName.NUMBER))
                    .addModifiers(Modifier.STATIC, Modifier.READONLY)
                    .initializer("new Map()")
                    .build())
            .addProperty(
                PropertySpec.builder("onEvent", TypeName.lambda(onEventParam, TypeName.VOID))
                    .initializer(
                        "%L",
                        FunctionSpec.builder("onEvent")
                            .arrow()
                            .addParameter("event", TypeName.STRING)
                            .returns(TypeName.VOID)
                            .addStatement("void event")
                            .build())
                    .build())
            .addProperty(
                PropertySpec.builder("engine", engine)
                    .addModifiers(Modifier.PRIVATE, Modifier.READONLY)
                    .initializer("engine")
                    .build())
            .addProperty(
                PropertySpec.builder("id", TypeName.STRING)
                    .addModifiers(Modifier.READONLY)
                    .initializer("%S", "widget")
                    .build())
            .constructor(
                FunctionSpec.constructorBuilder()
                    .addParameter("engine", engine)
                    .addStatement("super()")
                    .build())
            .addIndexable(
                FunctionSpec.indexableBuilder()
                    .addParameter("key", TypeName.STRING)
                    .returns(TypeName.implicit("unknown"))
                    .build())
            .addStaticBlock("Widget.registry.set(\"widget\", 1);\n")
            .addFunction(
                FunctionSpec.builder("greet")
                    .addModifiers(Modifier.PUBLIC, Modifier.OVERRIDE)
                    .addDecorator(
                        DecoratorSpec.builder(loggedDecorator)
                            .addParameter(null, "%S", "greet")
                            .addParameter("level", "%S", "info")
                            .build())
                    .returns(TypeName.STRING)
                    .addStatement("return this.#secret")
                    .build())
            .addFunction(
                FunctionSpec.builder("describe")
                    .addModifiers(Modifier.PROTECTED, Modifier.OVERRIDE)
                    .returns(TypeName.STRING)
                    .addStatement("return \"widget\"")
                    .build())
            .addFunction(
                FunctionSpec.builder("size")
                    .addModifiers(Modifier.PUBLIC, Modifier.GET)
                    .returns(TypeName.NUMBER)
                    .addStatement("return 1")
                    .build())
            .addFunction(
                FunctionSpec.builder("size")
                    .addModifiers(Modifier.PUBLIC, Modifier.SET)
                    .addParameter("value", TypeName.NUMBER)
                    .addStatement("void value")
                    .build())
            .addFunction(
                FunctionSpec.builder("items")
                    .generator()
                    .returns(TypeName.parameterizedType(TypeName.GENERATOR, TypeName.NUMBER))
                    .addStatement("yield 1")
                    .build())
            .addFunction(
                FunctionSpec.builder("create")
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                    .addParameter(
                        ParameterSpec.builder("engine", engine)
                            .addDecorator(DecoratorSpec.builder(loggedDecorator).build())
                            .build())
                    .returns(TypeName.implicit("Widget"))
                    .addStatement("return new Widget(engine)")
                    .build())
            .build());

    // ---- Namespace ----
    file.addModule(
        ModuleSpec.builder("Shapes")
            .addModifier(Modifier.EXPORT)
            .addInterface(InterfaceSpec.builder("Circle").addProperty("radius", TypeName.NUMBER).build())
            .build());

    file.addClass(
        ClassSpec.builder("Pair")
            .addModifiers(Modifier.EXPORT)
            .addProperty(
                PropertySpec.builder("left", TypeName.STRING)
                    .addModifiers(Modifier.PRIVATE, Modifier.READONLY)
                    .initializer("left")
                    .build())
            .addProperty(
                PropertySpec.builder("right", TypeName.STRING)
                    .addModifiers(Modifier.PRIVATE, Modifier.READONLY)
                    .initializer("right")
                    .build())
            .constructor(
                FunctionSpec.constructorBuilder()
                    .addParameter("left", TypeName.STRING)
                    .addParameter("right", TypeName.STRING)
                    .build())
            .build());

    file.addModule(
        ModuleSpec.builder("Ambient")
            .addModifier(Modifier.DECLARE)
            .addInterface(InterfaceSpec.builder("Host").addProperty("version", TypeName.STRING).build())
            .build());

    // ---- Top-level variables and exports ----
    file.addProperty(PropertySpec.builder("defaultLogger", logger).addModifiers(Modifier.LET).build());
    file.addProperty(
        PropertySpec.builder("VERSION", TypeName.STRING)
            .addModifiers(Modifier.CONST)
            .initializer("%S", "2.0.0")
            .build());

    file.addClass(
        ClassSpec.builder("Catalogue")
            .addModifiers(Modifier.EXPORT, Modifier.DEFAULT)
            .addProperty(
                PropertySpec.builder("entries", TypeName.arrayShorthandType(TypeName.STRING))
                    .addModifiers(Modifier.READONLY)
                    .initializer("[]")
                    .build())
            .build());

    file.addExport(ExportSpec.all("./engine"));
    file.addExport(ExportSpec.allAs("utilities", "./utils"));
    file.addExport(ExportSpec.named(List.of(ExportSpec.name("Options")), "./options", true));
    List<ExportSpec.Name> gadget = new ArrayList<>();
    gadget.add(ExportSpec.name("Widget", "Gadget"));
    file.addExport(ExportSpec.named(gadget, null, false));

    return file.build();
  }

  static String emit() throws IOException {
    StringWriter out = new StringWriter();
    spec().writeTo(out);
    return out.toString();
  }
}
