/*
 * Copyright 2017 Outfox, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.outfoxx.typescriptpoet.test

import io.outfoxx.typescriptpoet.ClassSpec
import io.outfoxx.typescriptpoet.CodeBlock
import io.outfoxx.typescriptpoet.DecoratorSpec
import io.outfoxx.typescriptpoet.EnumSpec
import io.outfoxx.typescriptpoet.ExportSpec
import io.outfoxx.typescriptpoet.FileSpec
import io.outfoxx.typescriptpoet.FunctionSpec
import io.outfoxx.typescriptpoet.InterfaceSpec
import io.outfoxx.typescriptpoet.Modifier
import io.outfoxx.typescriptpoet.ModuleSpec
import io.outfoxx.typescriptpoet.ParameterSpec
import io.outfoxx.typescriptpoet.PropertySpec
import io.outfoxx.typescriptpoet.SymbolSpec
import io.outfoxx.typescriptpoet.TypeAliasSpec
import io.outfoxx.typescriptpoet.TypeName
import io.outfoxx.typescriptpoet.TypeName.Mapped
import java.io.StringWriter

/**
 * One file exercising every TypeScript construct the library can emit, each used once.
 *
 * This is the single source of truth for the integration test: [KitchenSinkTests] emits it
 * and compares against `src/test/resources/kitchen-sink.ts`, then hands the same output to
 * the real `tsc`. Adding a construct to the library means adding it here.
 */
// Large by construction: it holds one of everything, and grows by one each time the library
// learns a construct. Splitting it would scatter the order it shares with the golden file.
@Suppress("LargeClass")
object KitchenSink {

  /** Extra modules the sink imports from, written alongside it so `tsc` can resolve them. */
  val companionModules: Map<String, String> = mapOf(
    "engine.ts" to "export class Engine { start(): void {} }\n",
    "logger.ts" to "export default class Logger { log(message: string): void {} }\n",
    "utils.ts" to "export function identity<T>(value: T): T { return value; }\n",
    "options.ts" to "export interface Options { verbose: boolean }\n",
    "polyfill.ts" to "export {};\ndeclare global { var polyfillLoaded: boolean; }\n",
    // The module an augment import points at: it adds a member to a type declared elsewhere
    // and exports nothing of its own, which is why it is imported for its side effect.
    "engine-boost.ts" to
      "import \"./engine\";\n" +
      "declare module \"./engine\" {\n  interface Engine {\n    boost(): void;\n  }\n}\n",
    "decorators.ts" to
      "export function sealed(...args: any[]): any {}\n" +
      "export function logged(...args: any[]): any {}\n",
  )

  // One deliberately linear function: it builds every construct in the order they appear in
  // the golden file, and splitting it would scatter that order across helpers.
  @Suppress("LongMethod")
  fun spec(): FileSpec {
    val t = TypeName.typeVariable("T")
    val k = TypeName.typeVariable("K")
    val person = TypeName.implicit("Person")

    val engine = TypeName.namedImport("Engine", "./engine")
    val logger = TypeName.defaultImport("Logger", "./logger")
    val options = TypeName.namedImport("Options", "./options", typeOnly = true)
    val sealedDecorator = SymbolSpec.importsName("sealed", "./decorators")
    val loggedDecorator = SymbolSpec.importsName("logged", "./decorators")

    val file = FileSpec.builder("kitchen-sink")
      .addComment("Generated by TypeScriptPoet. Do not edit.\n")

    // ---- Imports -------------------------------------------------------------------
    // All five import forms appear here: named, default, namespace, type-only and
    // side-effect. A side-effect import carries no binding of its own, so it is only
    // emitted when something references the symbol -- hence the statement below, which
    // reads a global the companion module declares.
    file.addCode(CodeBlock.of("%Q;\n", SymbolSpec.sideEffect("polyfillLoaded", "./polyfill")))

    // ---- Interfaces ----------------------------------------------------------------
    // Person covers the ordinary members: required, optional (`?`) and readonly. Callable
    // covers the two forms an interface has that a class does not -- a call signature and
    // an index signature -- which is why Widget implements Identified instead: a class
    // cannot satisfy a call signature.
    file.addInterface(
      InterfaceSpec.builder("Person")
        .addModifiers(Modifier.EXPORT)
        .addTSDoc("A person, as described by the source metadata.\n")
        .addProperty("name", TypeName.STRING)
        .addProperty("age", TypeName.NUMBER, optional = true)
        .addProperty(
          PropertySpec.builder("id", TypeName.STRING)
            .addModifiers(Modifier.READONLY)
            .build(),
        )
        .build(),
    )

    file.addInterface(
      InterfaceSpec.builder("Callable")
        .addModifiers(Modifier.EXPORT)
        .callable(
          FunctionSpec.callableBuilder()
            .addModifiers(Modifier.ABSTRACT)
            .addParameter("value", TypeName.STRING)
            .returns(TypeName.NUMBER)
            .build(),
        )
        .addIndexable(
          FunctionSpec.indexableBuilder()
            .addModifiers(Modifier.ABSTRACT)
            .addParameter("key", TypeName.STRING)
            .returns(TypeName.implicit("unknown"))
            .build(),
        )
        .build(),
    )

    file.addInterface(
      InterfaceSpec.builder("Identified")
        .addModifiers(Modifier.EXPORT)
        .addProperty(
          PropertySpec.builder("id", TypeName.STRING)
            .addModifiers(Modifier.READONLY)
            .build(),
        )
        .build(),
    )

    // An interface extending another. Only an interface has this: a class reaches the same
    // shape through superClass or addMixin, which are different keywords.
    file.addInterface(
      InterfaceSpec.builder("Labelled")
        .addModifiers(Modifier.EXPORT)
        .addSuperInterface(TypeName.implicit("Identified"))
        .addProperty("label", TypeName.STRING)
        .build(),
    )

    // ---- Type aliases: the whole type system ---------------------------------------
    // TypeAliasSpec is only `type Name<Vars> = %T`, so it inherits every TypeName for
    // free; this section is really the TypeName test surface.
    //
    // Three of these exist to pin down precedence rather than syntax: MixedArray and
    // KeysOfEither must parenthesise their unions, because `A | B[]` and `keyof A | B`
    // otherwise re-associate into something the caller did not ask for. Unwrap is the same
    // point for `infer`, which would read as `infer (U[])` unparenthesised.
    file.addTypeAlias(TypeAliasSpec.builder("PersonKey", TypeName.keyOf(person)).build())
    file.addTypeAlias(
      TypeAliasSpec.builder("PersonName", TypeName.indexedAccess(person, TypeName.implicit("\"name\""))).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("Names", TypeName.readOnly(TypeName.arrayShorthandType(TypeName.STRING))).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("Engines", TypeName.arrayType(engine)).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("Registry", TypeName.mapType(TypeName.STRING, TypeName.NUMBER)).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("Unique", TypeName.setType(TypeName.STRING)).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "Coordinates",
        TypeName.readOnly(
          TypeName.tupleType(
            listOf(
              TypeName.tupleMember(TypeName.NUMBER, label = "x"),
              TypeName.tupleMember(TypeName.NUMBER, label = "y", optional = true),
            ),
          ),
        ),
      ).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "Rest",
        TypeName.tupleType(
          listOf(
            TypeName.tupleMember(TypeName.STRING),
            TypeName.tupleMember(TypeName.arrayShorthandType(TypeName.NUMBER), label = "rest", rest = true),
          ),
        ),
      ).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("Choice", TypeName.unionType(TypeName.STRING, TypeName.NUMBER, TypeName.NULL)).build(),
    )
    // The two wrapped forms a union takes, which exist to be checked by Prettier rather than
    // only asserted in a test: LocationLabelKind is too long as a declaration but fits on
    // one indented line, and Verbose does not fit even there, so it goes one per line.
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "LocationLabelKind",
        TypeName.unionType(
          TypeName.literal("MARKETPLACE"),
          TypeName.literal("DISTRICT"),
          TypeName.literal("COUNTRY"),
          TypeName.literal("UNKNOWN"),
        ),
      ).addModifiers(Modifier.EXPORT).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "Verbose",
        TypeName.unionType(*(1..4).map { TypeName.literal("PARTITION_KEY_CANDIDATE_$it") }.toTypedArray()),
      ).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("Both", TypeName.intersectionType(person, options)).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "Anon",
        TypeName.anonymousType(
          listOf(
            TypeName.Anonymous.Member("label", TypeName.STRING, false),
            TypeName.Anonymous.Member("hint", TypeName.STRING, true),
          ),
        ),
      ).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "MixedArray",
        TypeName.arrayShorthandType(TypeName.unionType(TypeName.STRING, TypeName.NUMBER)),
      )
        .build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("KeysOfEither", TypeName.keyOf(TypeName.unionType(person, options))).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("Handler", TypeName.lambda("event" to TypeName.STRING, returnType = TypeName.VOID)).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "Identity",
        TypeName.genericLambda(
          typeVariables = listOf(TypeName.typeVariable("V")),
          parameters = mapOf("value" to TypeName.typeVariable("V")),
          returnType = TypeName.typeVariable("V"),
        ),
      ).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("EngineFactory", TypeName.constructorType(emptyMap(), engine)).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "AbstractEngineFactory",
        TypeName.constructorType(emptyMap(), engine, abstract = true),
      ).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "Bounded",
        TypeName.lambda(returnType = TypeName.typeVariable("B")),
      ).addTypeVariable(
        TypeName.typeVariable("B", TypeName.bound(person)),
      ).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "Producer",
        TypeName.lambda(returnType = TypeName.typeVariable("O")),
      ).addTypeVariable(TypeName.typeVariable("O", variance = TypeName.TypeVariable.Variance.OUT)).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "Unwrap",
        TypeName.conditionalType(
          t,
          TypeName.arrayShorthandType(TypeName.infer("U")),
          TypeName.typeVariable("U"),
          TypeName.NEVER,
        ),
      ).addTypeVariable(t).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "Mutable",
        TypeName.mappedType(
          keyName = "K",
          constraint = TypeName.keyOf(t),
          valueType = TypeName.indexedAccess(t, k),
          readonly = Mapped.Change.REMOVE,
          optional = Mapped.Change.ADD,
        ),
      ).addTypeVariable(t).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "Getters",
        TypeName.mappedType(
          keyName = "K",
          constraint = TypeName.keyOf(t),
          valueType = TypeName.indexedAccess(t, k),
          asClause = TypeName.templateLiteralType(
            "get",
            TypeName.parameterizedType(
              TypeName.implicit("Capitalize"),
              TypeName.parameterizedType(TypeName.implicit("Extract"), k, TypeName.STRING),
            ),
          ),
        ),
      ).addTypeVariable(t).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("TypeOfEngine", TypeName.typeOf(engine)).build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("Lookup", TypeName.recordType(TypeName.STRING, TypeName.NUMBER)).build(),
    )
    // Bounds with more than one constraint. The first bound's combiner is unused -- it is the
    // separator between bounds, not a prefix -- so `C` reads `string | number` and `W` reads
    // `Person & Options`. `P` carries the other thing a bound can hold, the `keyof` modifier,
    // which is a bound modifier rather than the `keyof` type operator that `PersonKey` uses.
    // Kept narrow on purpose: a type parameter list does not break on width yet, so a wider
    // one here would be output Prettier rewrites. See the width issue for that.
    file.addTypeAlias(
      TypeAliasSpec.builder(
        "Choose",
        TypeName.lambda("value" to TypeName.typeVariable("C"), returnType = TypeName.VOID),
      )
        .addTypeVariable(
          TypeName.typeVariable("C", TypeName.unionBound(TypeName.STRING), TypeName.unionBound(TypeName.NUMBER)),
        )
        .build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("Keyed", TypeName.lambda("key" to TypeName.typeVariable("P"), returnType = TypeName.VOID))
        .addTypeVariable(TypeName.typeVariable("P", TypeName.unionBound(person, keyOf = true)))
        .build(),
    )
    file.addTypeAlias(
      TypeAliasSpec.builder("Merged", TypeName.lambda(returnType = TypeName.typeVariable("W")))
        .addTypeVariable(TypeName.typeVariable("W", TypeName.bound(person), TypeName.intersectBound(options)))
        .build(),
    )

    // ---- Enums ---------------------------------------------------------------------
    // Direction is a string enum, Flags a const enum with a computed value. The initializer
    // is an opaque CodeBlock, which is why both shapes work without EnumSpec knowing about
    // either.
    file.addEnum(
      EnumSpec.builder("Direction")
        .addModifiers(Modifier.EXPORT)
        .addConstant("Up", CodeBlock.of("%S", "UP"))
        .addConstant("Down", CodeBlock.of("%S", "DOWN"))
        .build(),
    )
    file.addEnum(
      EnumSpec.builder("Flags")
        .addModifiers(Modifier.CONST)
        .addConstant("None", CodeBlock.of("0"))
        .addConstant("All", CodeBlock.of("1 << 2"))
        .build(),
    )

    // ---- Functions -----------------------------------------------------------------
    // Return-position constructs that are not types: `value is Person`, `asserts value is
    // Person` and bare `asserts value`. These are modelled separately from returnType
    // because a predicate is legal only in return position and depends on a parameter name.
    //
    // Then the parameter forms -- default values, optional, rest, and both destructuring
    // patterns -- and an overload group, which is N body-less signatures followed by one
    // implementation, all sharing a name.
    file.addFunction(
      FunctionSpec.builder("isPerson")
        .addModifiers(Modifier.EXPORT)
        .addTSDoc("Narrows an unknown value to %L.\n", "Person")
        .addParameter("value", TypeName.implicit("unknown"))
        .returnsIs("value", person)
        .addStatement("return typeof value === \"object\" && value !== null && \"name\" in value")
        .build(),
    )
    file.addFunction(
      FunctionSpec.builder("assertPerson")
        .addParameter("value", TypeName.implicit("unknown"))
        .returnsAsserts("value", person)
        .addStatement("if (!isPerson(value)) throw new Error(\"not a person\")")
        .build(),
    )
    file.addFunction(
      FunctionSpec.builder("assertReady")
        .addParameter("value", TypeName.implicit("unknown"))
        .returnsAsserts("value")
        .addStatement("if (!value) throw new Error(\"not ready\")")
        .build(),
    )
    file.addFunction(
      FunctionSpec.builder("pick")
        .addTypeVariable(TypeName.typeVariable("C", const = true))
        .addParameter("value", TypeName.typeVariable("C"))
        .returns(TypeName.typeVariable("C"))
        .addStatement("return value")
        .build(),
    )
    file.addFunction(
      FunctionSpec.builder("describe")
        .thisParameter(person)
        .returns(TypeName.STRING)
        .addStatement("return this.name")
        .build(),
    )
    file.addFunction(
      FunctionSpec.builder("load")
        .addModifiers(Modifier.ASYNC)
        .returns(TypeName.parameterizedType(TypeName.PROMISE, TypeName.STRING))
        .addStatement("return \"loaded\"")
        .build(),
    )
    file.addFunction(
      FunctionSpec.builder("counter")
        .generator()
        .returns(TypeName.parameterizedType(TypeName.GENERATOR, TypeName.NUMBER))
        .addStatement("yield 1")
        .build(),
    )
    file.addFunction(
      FunctionSpec.builder("stream")
        .addModifiers(Modifier.ASYNC)
        .generator()
        .returns(TypeName.parameterizedType(TypeName.implicit("AsyncGenerator"), TypeName.NUMBER))
        .addStatement("yield 1")
        .build(),
    )
    file.addFunction(
      FunctionSpec.builder("greet")
        .addParameter(
          ParameterSpec.builder("greeting", TypeName.STRING)
            .defaultValue("%S", "hello")
            .build(),
        )
        .addParameter("name", TypeName.STRING, optional = true)
        .restParameter("extras", TypeName.arrayShorthandType(TypeName.STRING))
        .returns(TypeName.STRING)
        .addStatement("return [greeting, name, ...extras].join(\" \")")
        .build(),
    )
    file.addFunction(
      FunctionSpec.builder("configure")
        .addParameter(
          ParameterSpec.builder("options", options)
            .destructure(ParameterSpec.objectPattern(ParameterSpec.binding("verbose", "loud")))
            .build(),
        )
        .returns(TypeName.BOOLEAN)
        .addStatement("return loud")
        .build(),
    )
    file.addFunction(
      FunctionSpec.builder("swap")
        .addParameter(
          ParameterSpec.builder("pair", TypeName.tupleType(TypeName.STRING, TypeName.STRING))
            .destructure(ParameterSpec.arrayPattern("first", "second"))
            .build(),
        )
        .returns(TypeName.tupleType(TypeName.STRING, TypeName.STRING))
        .addStatement("return [second, first]")
        .build(),
    )
    file.addFunction(
      FunctionSpec.builder("useUtils")
        .returns(TypeName.STRING)
        .addStatement("return %Q.identity(\"x\")", SymbolSpec.importsAll("utils", "./utils"))
        .build(),
    )
    FunctionSpec.overloads(
      signatures = listOf(
        FunctionSpec.builder("parse").addParameter("value", TypeName.STRING).returns(TypeName.STRING).build(),
        FunctionSpec.builder("parse").addParameter("value", TypeName.NUMBER).returns(TypeName.NUMBER).build(),
      ),
      implementation = FunctionSpec.builder("parse")
        .addParameter("value", TypeName.unionType(TypeName.STRING, TypeName.NUMBER))
        .returns(TypeName.unionType(TypeName.STRING, TypeName.NUMBER))
        .addStatement("return value")
        .build(),
    ).forEach { file.addFunction(it) }

    // Control flow, which is the one part of a body the library lays out rather than taking
    // verbatim: the braces, the indent between them and the `}` before `else` are all its.
    file.addFunction(
      FunctionSpec.builder("classify")
        .addParameter("value", TypeName.NUMBER)
        .returns(TypeName.STRING)
        .beginControlFlow("if (value > 0)")
        .addStatement("return %S", "positive")
        .nextControlFlow("else if (value < 0)")
        .addStatement("return %S", "negative")
        .nextControlFlow("else")
        .addStatement("return %S", "zero")
        .endControlFlow()
        .build(),
    )

    // An augment import: a module imported for a member it adds to a type declared somewhere
    // else. It carries no binding of its own, so it is emitted next to the import of the
    // symbol it augments rather than on its own -- the sixth import form, and the reason
    // `boost` below resolves at all.
    file.addFunction(
      FunctionSpec.builder("boostEngine")
        .addParameter("engine", engine)
        .addStatement("engine.%Q()", SymbolSpec.augmented("boost", "./engine-boost", "Engine"))
        .build(),
    )

    // ---- Object literals -----------------------------------------------------------
    // All three member kinds at once: a property, shorthand, and a getter. The getter is
    // what a lazily-reached value is made of -- as a property, `depth` would be computed
    // where the object is built rather than where it is read -- and it is also why this
    // literal breaks: a getter body is a statement list, so it spans lines however short it
    // measures, and a member that spans lines breaks the literal holding it.
    file.addFunction(
      FunctionSpec.builder("node")
        .addModifiers(Modifier.EXPORT)
        .addParameter("path", TypeName.STRING)
        .addStatement(
          "return %L",
          CodeBlock.objectLiteral()
            .addProperty("kind", "%S", "node")
            .addShorthand("path")
            .addGetter("depth", "return path.split(%S).length", "/")
            .addProperty(
              "send",
              "%L",
              FunctionSpec.builder("send")
                .arrow()
                .addParameter("message", TypeName.STRING)
                .returns(TypeName.VOID)
                .addStatement("console.log(message)")
                .build(),
            )
            .build(),
        )
        .build(),
    )

    // ---- Classes -------------------------------------------------------------------
    // Base exercises abstract classes and abstract members; Widget exercises everything a
    // concrete class can carry. Note two things that are easy to get wrong:
    //
    // The `engine` property is promoted into the constructor signature, and the promoted
    // declaration takes its modifiers from the *property*, not from the constructor
    // parameter -- so `private readonly` lives on the PropertySpec.
    //
    // `#secret` needs no modifier: the name alone makes it private, and adding
    // Modifier.PRIVATE as well is rejected at build time.
    file.addClass(
      ClassSpec.builder("Base")
        .addModifiers(Modifier.EXPORT, Modifier.ABSTRACT)
        .addTypeVariable(TypeName.typeVariable("S", TypeName.bound(TypeName.STRING)))
        .addFunction(
          FunctionSpec.builder("greet")
            .addModifiers(Modifier.PUBLIC)
            .returns(TypeName.STRING)
            .addStatement("return \"hi\"")
            .build(),
        )
        .addFunction(
          FunctionSpec.builder("describe")
            .addModifiers(Modifier.PROTECTED, Modifier.ABSTRACT)
            .returns(TypeName.STRING)
            .build(),
        )
        .build(),
    )

    file.addClass(
      ClassSpec.builder("Widget")
        .addModifiers(Modifier.EXPORT)
        .addTSDoc("The widget the generator produces.\n")
        .addDecorator(DecoratorSpec.builder(sealedDecorator).build())
        .superClass(TypeName.parameterizedType(TypeName.implicit("Base"), TypeName.STRING))
        .addMixin(TypeName.implicit("Identified"))
        .addProperty(PropertySpec.builder("#secret", TypeName.STRING).initializer("%S", "s").build())
        // A decorator in property position, in the factory form: `@logged()` rather than
        // `@logged`. The two are different expressions, so which one is emitted is the
        // caller's to say and not inferred from whether there are parameters.
        .addProperty(
          PropertySpec.builder("later", TypeName.STRING)
            .definiteAssignment()
            .addDecorator(DecoratorSpec.builder(loggedDecorator).asFactory().build())
            .build(),
        )
        .addProperty(
          PropertySpec.builder("count", TypeName.NUMBER)
            .addModifiers(Modifier.ACCESSOR)
            .initializer("0")
            .build(),
        )
        .addProperty(
          PropertySpec.builder("registry", TypeName.mapType(TypeName.STRING, TypeName.NUMBER))
            .addModifiers(Modifier.STATIC, Modifier.READONLY)
            .initializer("new Map()")
            .build(),
        )
        .addProperty(
          PropertySpec.builder("onEvent", TypeName.lambda("event" to TypeName.STRING, returnType = TypeName.VOID))
            .initializer(
              "%L",
              FunctionSpec.builder("onEvent")
                .arrow()
                .addParameter("event", TypeName.STRING)
                .returns(TypeName.VOID)
                .addStatement("void event")
                .build(),
            )
            .build(),
        )
        // Promoted to a constructor parameter property; the promoted declaration takes its
        // modifiers from the property, not from the constructor parameter.
        .addProperty(
          PropertySpec.builder("engine", engine)
            .addModifiers(Modifier.PRIVATE, Modifier.READONLY)
            .initializer("engine")
            .build(),
        )
        .addProperty(
          PropertySpec.builder("id", TypeName.STRING)
            .addModifiers(Modifier.READONLY)
            .initializer("%S", "widget")
            .build(),
        )
        .constructor(
          FunctionSpec.constructorBuilder()
            .addParameter("engine", engine)
            .addStatement("super()")
            .build(),
        )
        .addIndexable(
          FunctionSpec.indexableBuilder()
            .addParameter("key", TypeName.STRING)
            .returns(TypeName.implicit("unknown"))
            .build(),
        )
        .addStaticBlock("Widget.registry.set(\"widget\", 1);\n")
        // Decorator parameters, positional and named. TypeScript has no named arguments, so a
        // named one is emitted as a comment against the value it labels.
        .addFunction(
          FunctionSpec.builder("greet")
            .addModifiers(Modifier.PUBLIC, Modifier.OVERRIDE)
            .addDecorator(
              DecoratorSpec.builder(loggedDecorator)
                .addParameter(null, "%S", "greet")
                .addParameter("level", "%S", "info")
                .build(),
            )
            .returns(TypeName.STRING)
            .addStatement("return this.#secret")
            .build(),
        )
        .addFunction(
          FunctionSpec.builder("describe")
            .addModifiers(Modifier.PROTECTED, Modifier.OVERRIDE)
            .returns(TypeName.STRING)
            .addStatement("return \"widget\"")
            .build(),
        )
        .addFunction(
          FunctionSpec.builder("size")
            .addModifiers(Modifier.PUBLIC, Modifier.GET)
            .returns(TypeName.NUMBER)
            .addStatement("return 1")
            .build(),
        )
        .addFunction(
          FunctionSpec.builder("size")
            .addModifiers(Modifier.PUBLIC, Modifier.SET)
            .addParameter("value", TypeName.NUMBER)
            .addStatement("void value")
            .build(),
        )
        .addFunction(
          FunctionSpec.builder("items")
            .generator()
            .returns(TypeName.parameterizedType(TypeName.GENERATOR, TypeName.NUMBER))
            .addStatement("yield 1")
            .build(),
        )
        // A decorator in parameter position, the third place one can appear.
        .addFunction(
          FunctionSpec.builder("create")
            .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
            .addParameter(
              ParameterSpec.builder("engine", engine)
                .addDecorator(DecoratorSpec.builder(loggedDecorator).build())
                .build(),
            )
            .returns(TypeName.implicit("Widget"))
            .addStatement("return new Widget(engine)")
            .build(),
        )
        .build(),
    )

    // ---- Namespace -----------------------------------------------------------------
    // Namespaces and modules differ only in keyword; ModuleSpec.Kind picks which.
    file.addModule(
      ModuleSpec.builder("Shapes")
        .addModifier(Modifier.EXPORT)
        .addInterface(
          InterfaceSpec.builder("Circle")
            .addProperty("radius", TypeName.NUMBER)
            .build(),
        )
        .build(),
    )

    // Two parameter properties in one constructor, which is the list Prettier breaks whatever
    // its width -- one on its own, as Widget has, stays inline.
    file.addClass(
      ClassSpec.builder("Pair")
        .addModifiers(Modifier.EXPORT)
        .addProperty(
          PropertySpec.builder("left", TypeName.STRING)
            .addModifiers(Modifier.PRIVATE, Modifier.READONLY)
            .initializer("left")
            .build(),
        )
        .addProperty(
          PropertySpec.builder("right", TypeName.STRING)
            .addModifiers(Modifier.PRIVATE, Modifier.READONLY)
            .initializer("right")
            .build(),
        )
        .constructor(
          FunctionSpec.constructorBuilder()
            .addParameter("left", TypeName.STRING)
            .addParameter("right", TypeName.STRING)
            // A body only because an empty one is emitted as `{\n}` where Prettier writes
            // `{}`, which is its own bug and not this one's to carry.
            .addStatement("if (left === right) throw new Error(%S)", "duplicate")
            .build(),
        )
        .build(),
    )

    // `declare`, which says a thing exists without defining it. It is exclusive with `export`
    // on a module, so it needs one of its own rather than a modifier on Shapes.
    file.addModule(
      ModuleSpec.builder("Ambient")
        .addModifier(Modifier.DECLARE)
        .addInterface(
          InterfaceSpec.builder("Host")
            .addProperty("version", TypeName.STRING)
            .build(),
        )
        .build(),
    )

    // ---- Top-level variables and exports --------------------------------------------
    // A top-level property is a variable declaration, so it must carry exactly one of
    // CONST, LET or VAR -- unlike every other member, where those modifiers are rejected.
    //
    // The four export statements are the forms that are not simply a modifier on a
    // declaration. `export =` is absent on purpose: it cannot coexist with any ES export in
    // one file, which FileSpec enforces, so it cannot appear here at all.
    file.addProperty(
      PropertySpec.builder("defaultLogger", logger)
        .addModifiers(Modifier.LET)
        .build(),
    )
    file.addProperty(
      PropertySpec.builder("VERSION", TypeName.STRING)
        .addModifiers(Modifier.CONST)
        .initializer("%S", "2.0.0")
        .build(),
    )

    // `export default` is a modifier rather than a statement, and a file may carry one.
    file.addClass(
      ClassSpec.builder("Catalogue")
        .addModifiers(Modifier.EXPORT, Modifier.DEFAULT)
        .addProperty(
          PropertySpec.builder("entries", TypeName.arrayShorthandType(TypeName.STRING))
            .addModifiers(Modifier.READONLY)
            .initializer("[]")
            .build(),
        )
        .build(),
    )

    file.addExport(ExportSpec.all("./engine"))
    file.addExport(ExportSpec.allAs("utilities", "./utils"))
    file.addExport(ExportSpec.named(listOf(ExportSpec.name("Options")), from = "./options", typeOnly = true))
    file.addExport(ExportSpec.named(listOf(ExportSpec.name("Widget", "Gadget"))))

    return file.build()
  }

  fun emit(): String {
    val out = StringWriter()
    spec().writeTo(out)
    return out.toString()
  }
}
