/*
 * Copyright 2017 Outfox, Inc.
 * Copyright 2026 LL Data ApS
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dk.lldata.typescriptpoet.test

import dk.lldata.typescriptpoet.CodeBlock
import dk.lldata.typescriptpoet.ExportSpec
import dk.lldata.typescriptpoet.FileSpec
import dk.lldata.typescriptpoet.FunctionSpec
import dk.lldata.typescriptpoet.Modifier
import dk.lldata.typescriptpoet.ParameterSpec
import dk.lldata.typescriptpoet.SymbolSpec
import dk.lldata.typescriptpoet.TypeName
import dk.lldata.typescriptpoet.TypeName.Mapped
import dk.lldata.typescriptpoet.dsl.abstract
import dk.lldata.typescriptpoet.dsl.accessor
import dk.lldata.typescriptpoet.dsl.and
import dk.lldata.typescriptpoet.dsl.anonymous
import dk.lldata.typescriptpoet.dsl.any
import dk.lldata.typescriptpoet.dsl.argument
import dk.lldata.typescriptpoet.dsl.arrow
import dk.lldata.typescriptpoet.dsl.async
import dk.lldata.typescriptpoet.dsl.body
import dk.lldata.typescriptpoet.dsl.boolean
import dk.lldata.typescriptpoet.dsl.call
import dk.lldata.typescriptpoet.dsl.clazz
import dk.lldata.typescriptpoet.dsl.code
import dk.lldata.typescriptpoet.dsl.comment
import dk.lldata.typescriptpoet.dsl.const
import dk.lldata.typescriptpoet.dsl.constant
import dk.lldata.typescriptpoet.dsl.constructor
import dk.lldata.typescriptpoet.dsl.declare
import dk.lldata.typescriptpoet.dsl.decorator
import dk.lldata.typescriptpoet.dsl.default
import dk.lldata.typescriptpoet.dsl.enum
import dk.lldata.typescriptpoet.dsl.export
import dk.lldata.typescriptpoet.dsl.expression
import dk.lldata.typescriptpoet.dsl.extends
import dk.lldata.typescriptpoet.dsl.file
import dk.lldata.typescriptpoet.dsl.function
import dk.lldata.typescriptpoet.dsl.get
import dk.lldata.typescriptpoet.dsl.getter
import dk.lldata.typescriptpoet.dsl.implements
import dk.lldata.typescriptpoet.dsl.index
import dk.lldata.typescriptpoet.dsl.interfaze
import dk.lldata.typescriptpoet.dsl.labelled
import dk.lldata.typescriptpoet.dsl.let
import dk.lldata.typescriptpoet.dsl.literal
import dk.lldata.typescriptpoet.dsl.member
import dk.lldata.typescriptpoet.dsl.namespace
import dk.lldata.typescriptpoet.dsl.never
import dk.lldata.typescriptpoet.dsl.newInstance
import dk.lldata.typescriptpoet.dsl.null_
import dk.lldata.typescriptpoet.dsl.number
import dk.lldata.typescriptpoet.dsl.obj
import dk.lldata.typescriptpoet.dsl.optional
import dk.lldata.typescriptpoet.dsl.optionalMember
import dk.lldata.typescriptpoet.dsl.or
import dk.lldata.typescriptpoet.dsl.overloads
import dk.lldata.typescriptpoet.dsl.override
import dk.lldata.typescriptpoet.dsl.parameter
import dk.lldata.typescriptpoet.dsl.private
import dk.lldata.typescriptpoet.dsl.property
import dk.lldata.typescriptpoet.dsl.protected
import dk.lldata.typescriptpoet.dsl.public
import dk.lldata.typescriptpoet.dsl.readonly
import dk.lldata.typescriptpoet.dsl.rest
import dk.lldata.typescriptpoet.dsl.set
import dk.lldata.typescriptpoet.dsl.shorthand
import dk.lldata.typescriptpoet.dsl.static
import dk.lldata.typescriptpoet.dsl.string
import dk.lldata.typescriptpoet.dsl.tsDoc
import dk.lldata.typescriptpoet.dsl.type
import dk.lldata.typescriptpoet.dsl.typeArgument
import dk.lldata.typescriptpoet.dsl.typeParam
import dk.lldata.typescriptpoet.dsl.union
import dk.lldata.typescriptpoet.dsl.unknown
import dk.lldata.typescriptpoet.dsl.void
import java.io.StringWriter

/**
 * [KitchenSink] written with the Kotlin DSL instead of the builders, member for member and
 * comment for comment, so the two can be read side by side.
 *
 * [KitchenSinkDslTests] asserts the two emit the same file, byte for byte. That is what makes
 * this a comparison rather than two files that merely look similar.
 */
@Suppress("LargeClass")
object KitchenSinkDsl {

  @Suppress("LongMethod")
  fun spec(): FileSpec {
    val t = TypeName.typeVariable("T")
    val k = TypeName.typeVariable("K")
    val person = TypeName.implicit("Person")

    val engine = TypeName.namedImport("Engine", "./engine")
    val logger = TypeName.defaultImport("Logger", "./logger")
    val options = TypeName.namedImport("Options", "./options", typeOnly = true)
    val sealedDecorator = SymbolSpec.importsName("sealed", "./decorators")
    val loggedDecorator = SymbolSpec.importsName("logged", "./decorators")

    return file("kitchen-sink") {
      comment("Generated by TypeScriptPoet. Do not edit.\n")

      // ---- Imports -------------------------------------------------------------------
      // All five import forms appear here: named, default, namespace, type-only and
      // side-effect. A side-effect import carries no binding of its own, so it is only
      // emitted when something references the symbol -- hence the statement below, which
      // reads a global the companion module declares.
      code("%Q;\n", SymbolSpec.sideEffect("polyfillLoaded", "./polyfill"))

      // ---- Interfaces ----------------------------------------------------------------
      // Person covers the ordinary members: required, optional (`?`) and readonly. Callable
      // covers the two forms an interface has that a class does not -- a call signature and
      // an index signature -- which is why Widget implements Identified instead: a class
      // cannot satisfy a call signature.
      interfaze("Person", export) {
        tsDoc("A person, as described by the source metadata.\n")
        property("name", string)
        optional("age", number)
        property("id", string, readonly)
      }

      interfaze("Callable", export) {
        call(abstract) {
          parameter("value", string)
          returns(number)
        }
        index(abstract) {
          parameter("key", string)
          returns(unknown)
        }
      }

      interfaze("Identified", export) {
        property("id", string, readonly)
      }

      // An interface extending another. Only an interface has this: a class reaches the same
      // shape through superClass or addMixin, which are different keywords.
      interfaze("Labelled", export) {
        extends(TypeName.implicit("Identified"))
        property("label", string)
      }

      // ---- Type aliases: the whole type system ---------------------------------------
      // TypeAliasSpec is only `type Name<Vars> = %T`, so it inherits every TypeName for
      // free; this section is really the TypeName test surface.
      //
      // Three of these exist to pin down precedence rather than syntax: MixedArray and
      // KeysOfEither must parenthesise their unions, because `A | B[]` and `keyof A | B`
      // otherwise re-associate into something the caller did not ask for. Unwrap is the same
      // point for `infer`, which would read as `infer (U[])` unparenthesised.
      type("PersonKey", TypeName.keyOf(person))
      type("PersonName", TypeName.indexedAccess(person, TypeName.implicit("\"name\"")))
      type("Names", TypeName.readOnly(TypeName.arrayShorthandType(string)))
      type("Engines", TypeName.arrayType(engine))
      type("Registry", TypeName.mapType(string, number))
      type("Unique", TypeName.setType(string))
      type(
        "Coordinates",
        TypeName.readOnly(
          TypeName.tupleType(
            listOf(
              TypeName.tupleMember(number, label = "x"),
              TypeName.tupleMember(number, label = "y", optional = true),
            ),
          ),
        ),
      )
      type(
        "Rest",
        TypeName.tupleType(
          listOf(
            TypeName.tupleMember(string),
            TypeName.tupleMember(TypeName.arrayShorthandType(number), label = "rest", rest = true),
          ),
        ),
      )
      type("Choice", string or number or null_)
      // The two wrapped forms a union takes, which exist to be checked by Prettier rather than
      // only asserted in a test: LocationLabelKind is too long as a declaration but fits on
      // one indented line, and Verbose does not fit even there, so it goes one per line.
      type(
        "LocationLabelKind",
        literal("MARKETPLACE") or literal("DISTRICT") or literal("COUNTRY") or literal("UNKNOWN"),
        export,
      )
      type("Verbose", union((1..4).map { literal("PARTITION_KEY_CANDIDATE_$it") }))
      type("Both", person and options)
      type("Anon", anonymous(member("label", string), optionalMember("hint", string)))
      type("MixedArray", TypeName.arrayShorthandType(string or number))
      type("KeysOfEither", TypeName.keyOf(person or options))
      type("Handler", TypeName.lambda("event" to string, returnType = void))
      type(
        "Identity",
        TypeName.genericLambda(
          typeVariables = listOf(TypeName.typeVariable("V")),
          parameters = mapOf("value" to TypeName.typeVariable("V")),
          returnType = TypeName.typeVariable("V"),
        ),
      )
      type("EngineFactory", TypeName.constructorType(emptyMap(), engine))
      type("AbstractEngineFactory", TypeName.constructorType(emptyMap(), engine, abstract = true))
      type("Bounded", TypeName.lambda(returnType = TypeName.typeVariable("B"))) {
        typeParam("B", TypeName.bound(person))
      }
      type("Producer", TypeName.lambda(returnType = TypeName.typeVariable("O"))) {
        typeParam("O", variance = TypeName.TypeVariable.Variance.OUT)
      }
      type(
        "Unwrap",
        TypeName.conditionalType(
          t,
          TypeName.arrayShorthandType(TypeName.infer("U")),
          TypeName.typeVariable("U"),
          never,
        ),
      ) { typeParam(t) }
      type(
        "Mutable",
        TypeName.mappedType(
          keyName = "K",
          constraint = TypeName.keyOf(t),
          valueType = TypeName.indexedAccess(t, k),
          readonly = Mapped.Change.REMOVE,
          optional = Mapped.Change.ADD,
        ),
      ) { typeParam(t) }
      type(
        "Getters",
        TypeName.mappedType(
          keyName = "K",
          constraint = TypeName.keyOf(t),
          valueType = TypeName.indexedAccess(t, k),
          asClause = TypeName.templateLiteralType(
            "get",
            TypeName.parameterizedType(
              TypeName.implicit("Capitalize"),
              TypeName.parameterizedType(TypeName.implicit("Extract"), k, string),
            ),
          ),
        ),
      ) { typeParam(t) }
      type("TypeOfEngine", TypeName.typeOf(engine))
      type("Lookup", TypeName.recordType(string, number))
      // Bounds with more than one constraint. The first bound's combiner is unused -- it is the
      // separator between bounds, not a prefix -- so `C` reads `string | number` and `W` reads
      // `Person & Options`. `P` carries the other thing a bound can hold, the `keyof` modifier,
      // which is a bound modifier rather than the `keyof` type operator that `PersonKey` uses.
      // Wide enough that the type parameter list has to break, which it also covers.
      type(
        "Constrained",
        TypeName.lambda(
          "value" to TypeName.typeVariable("C"),
          "key" to TypeName.typeVariable("P"),
          returnType = TypeName.typeVariable("W"),
        ),
      ) {
        typeParam("C", TypeName.unionBound(string), TypeName.unionBound(number))
        typeParam("P", TypeName.unionBound(person, keyOf = true))
        typeParam("W", TypeName.bound(person), TypeName.intersectBound(options))
      }

      // ---- Enums ---------------------------------------------------------------------
      // Direction is a string enum, Flags a const enum with a computed value. The initializer
      // is an opaque CodeBlock, which is why both shapes work without EnumSpec knowing about
      // either.
      enum("Direction", export) {
        constant("Up", "%S", "UP")
        constant("Down", "%S", "DOWN")
      }
      enum("Flags", const) {
        constant("None", "0")
        constant("All", "1 << 2")
      }

      // ---- Functions -----------------------------------------------------------------
      // Return-position constructs that are not types: `value is Person`, `asserts value is
      // Person` and bare `asserts value`. These are modelled separately from returnType
      // because a predicate is legal only in return position and depends on a parameter name.
      //
      // Then the parameter forms -- default values, optional, rest, and both destructuring
      // patterns -- and an overload group, which is N body-less signatures followed by one
      // implementation, all sharing a name.
      function("isPerson", export) {
        tsDoc("Narrows an unknown value to %L.\n", "Person")
        parameter("value", unknown)
        returnsIs("value", person)
        body {
          statement("return typeof value === \"object\" && value !== null && \"name\" in value")
        }
      }
      function("assertPerson") {
        parameter("value", unknown)
        returnsAsserts("value", person)
        body {
          statement("if (!isPerson(value)) throw new Error(\"not a person\")")
        }
      }
      function("assertReady") {
        parameter("value", unknown)
        returnsAsserts("value")
        body {
          statement("if (!value) throw new Error(\"not ready\")")
        }
      }
      function("pick") {
        typeParam("C", const = true)
        parameter("value", TypeName.typeVariable("C"))
        returns(TypeName.typeVariable("C"))
        body {
          statement("return value")
        }
      }
      function("describe") {
        thisParameter(person)
        returns(string)
        body {
          statement("return this.name")
        }
      }
      function("load", async) {
        returns(TypeName.parameterizedType(TypeName.PROMISE, string))
        body {
          statement("return \"loaded\"")
        }
      }
      function("counter") {
        generator()
        returns(TypeName.parameterizedType(TypeName.GENERATOR, number))
        body {
          statement("yield 1")
        }
      }
      function("stream", async) {
        generator()
        returns(TypeName.parameterizedType(TypeName.implicit("AsyncGenerator"), number))
        body {
          statement("yield 1")
        }
      }
      function("greet") {
        parameter("greeting", string) { defaultValue("%S", "hello") }
        parameter("name", string, optional = true)
        rest("extras", TypeName.arrayShorthandType(string))
        returns(string)
        body {
          statement("return [greeting, name, ...extras].join(\" \")")
        }
      }
      function("configure") {
        parameter("options", options) {
          destructure(ParameterSpec.objectPattern(ParameterSpec.binding("verbose", "loud")))
        }
        returns(boolean)
        body {
          statement("return loud")
        }
      }
      function("swap") {
        parameter("pair", TypeName.tupleType(string, string)) {
          destructure(ParameterSpec.arrayPattern("first", "second"))
        }
        returns(TypeName.tupleType(string, string))
        body {
          statement("return [second, first]")
        }
      }
      function("useUtils") {
        returns(string)
        body {
          statement("return %Q.identity(\"x\")", SymbolSpec.importsAll("utils", "./utils"))
        }
      }
      overloads(
        "parse",
        {
          parameter("value", string)
          returns(string)
        },
        {
          parameter("value", number)
          returns(number)
        },
      ) {
        parameter("value", string or number)
        returns(string or number)
        body { statement("return value") }
      }

      // Control flow, which is the one part of a body the library lays out rather than taking
      // verbatim: the braces, the indent between them and the `}` before `else` are all its.
      function("classify") {
        parameter("value", number)
        returns(string)

        body {
          begin("if (value > 0)")
          statement("return %S", "positive")
          next("else if (value < 0)")
          statement("return %S", "negative")
          next("else")
          statement("return %S", "zero")
          end()
        }
      }

      // An augment import: a module imported for a member it adds to a type declared somewhere
      // else. It carries no binding of its own, so it is emitted next to the import of the
      // symbol it augments rather than on its own -- the sixth import form, and the reason
      // `boost` below resolves at all.
      function("boostEngine") {
        parameter("engine", engine)
        body {
          statement("engine.%Q()", SymbolSpec.augmented("boost", "./engine-boost", "Engine"))
        }
      }

      // ---- Object literals -----------------------------------------------------------
      // All three member kinds at once: a property, shorthand, and a getter. The getter is
      // what a lazily-reached value is made of -- as a property, `depth` would be computed
      // where the object is built rather than where it is read -- and it is also why this
      // literal breaks: a getter body is a statement list, so it spans lines however short it
      // measures, and a member that spans lines breaks the literal holding it.
      function("node", export) {
        parameter("path", string)
        body {
          statement(
            "return %L",
            obj {
              property("kind", "%S", "node")
              shorthand("path")
              getter("depth", "return path.split(%S).length", "/")
              // A spec goes straight in as a member value; the `%L` that used to carry it
              // said nothing the argument does not.
              property(
                "send",
                arrow("send") {
                  parameter("message", string)
                  returns(void)
                  body { statement("console.log(message)") }
                },
              )
            },
          )
        }
      }

      // ---- Call expressions ----------------------------------------------------------
      // The construct that makes an argument list breakable. Written as a format string --
      // `statement("return %T(%L, config, options)", …)` -- the `, config, options)` is text
      // with no argument boundaries in it, so a writer cannot break the line where Prettier
      // would. Kept as a list, the arguments break together and one per line.
      //
      // `fetchResource` is over the width and breaks; `ping` fits and stays inline.
      function("loadDeviceConfiguration", export) {
        parameter("path", string)
        parameter("config", TypeName.namedImport("RequestConfig", "./fetch-resource"))
        returns(TypeName.promiseType(TypeName.implicit("Widget")))
        body {
          statement(
            "return %L",
            call(TypeName.namedImport("fetchResource", "./fetch-resource")) {
              typeArgument(TypeName.implicit("Widget"))
              argument(
                obj {
                  property("method", "%S", "POST")
                  shorthand("path")
                  property("retries", "%L", 3)
                },
              )
              argument("config")
              argument("undefined")
            },
          )
        }
      }

      function("ping") {
        body { statement("return %L", call("fetch") { argument("%S", "/ping") }) }
      }

      // A constructor call lays its arguments out the same way.
      function("emptyIndex") {
        returns(TypeName.mapType(string, number))
        body { statement("return %L", newInstance(TypeName.mapType(string, number))) }
      }

      // ---- Concise arrow bodies ------------------------------------------------------
      // `=> expr` rather than `=> { return expr; }`, which is what a reader would write for
      // a one-expression body. An object literal is parenthesised, since `=> {` opens a block.
      function("doubler", export) {
        returns(TypeName.lambda("value" to number, returnType = number))
        body {
          statement(
            "return %L",
            arrow("double") {
              parameter("value", number)
              expression("value * 2")
            },
          )
        }
      }

      function("wrap", export) {
        body {
          statement(
            "return %L",
            arrow("wrapOne") {
              parameter("value", number)
              expression(obj { shorthand("value") })
            },
          )
        }
      }

      // ---- Inline object types -------------------------------------------------------
      // An anonymous type carrying a comment per member. The comment is the reason it is not
      // an interface: it says what omitting the member means, which optionality alone does
      // not, without lifting the shape into a declaration nothing else refers to. A
      // documented member puts the type on several lines whatever it measures.
      function("listWidgets", export) {
        parameter(
          "args",
          anonymous(
            optionalMember("limit", number, CodeBlock.of("Server default: %L.\n", 20)),
            optionalMember("cursor", string),
            optionalMember("includeArchived", boolean),
          ),
          optional = true,
        )
        returns(TypeName.promiseType(TypeName.arrayShorthandType(unknown)))
        body {
          statement(
            "return %L",
            call(TypeName.namedImport("queryWidgets", "./fetch-resource")) { argument("args") },
          )
        }
      }

      // ---- Classes -------------------------------------------------------------------
      // Base exercises abstract classes and abstract members; Widget exercises everything a
      // concrete class can carry. Note two things that are easy to get wrong:
      //
      // The `engine` property is promoted into the constructor signature, and the promoted
      // declaration takes its modifiers from the *property*, not from the constructor
      // parameter -- so `private readonly` lives on the PropertySpec.
      //
      // `#secret` needs no modifier: the name alone makes it private, and adding
      // private as well is rejected at build time.
      clazz("Base", export, abstract) {
        typeParam("S", TypeName.bound(string))
        function("greet", public) {
          returns(string)
          body {
            statement("return \"hi\"")
          }
        }
        function("describe", protected, abstract) { returns(string) }
      }

      clazz("Widget", export) {
        tsDoc("The widget the generator produces.\n")
        decorator(sealedDecorator)
        extends(TypeName.parameterizedType(TypeName.implicit("Base"), string))
        implements(TypeName.implicit("Identified"))

        property("#secret", string) { initializer("%S", "s") }
        // A decorator in property position, in the factory form: `@logged()` rather than
        // `@logged`. The two are different expressions, so which one is emitted is the
        // caller's to say and not inferred from whether there are parameters.
        property("later", string) {
          definiteAssignment()
          decorator(loggedDecorator) { asFactory() }
        }
        property("count", number, accessor) { initializer("0") }
        property("registry", TypeName.mapType(string, number), static, readonly) {
          initializer("new Map()")
        }
        property("onEvent", TypeName.lambda("event" to string, returnType = void)) {
          initializer(
            "%L",
            arrow("onEvent") {
              parameter("event", string)
              returns(void)
              body {
                statement("void event")
              }
            },
          )
        }
        // Promoted to a constructor parameter property; the promoted declaration takes its
        // modifiers from the property, not from the constructor parameter.
        property("engine", engine, private, readonly) { initializer("engine") }
        property("id", string, readonly) { initializer("%S", "widget") }

        constructor {
          parameter("engine", engine)
          body {
            statement("super()")
          }
        }
        index {
          parameter("key", string)
          returns(unknown)
        }
        static("Widget.registry.set(\"widget\", 1);\n")

        // Decorator parameters, positional and named. TypeScript has no named arguments, so a
        // named one is emitted as a comment against the value it labels.
        function("greet", public, override) {
          decorator(loggedDecorator) {
            argument("%S", "greet")
            labelled("level", "%S", "info")
          }
          returns(string)
          body {
            statement("return this.#secret")
          }
        }
        function("describe", protected, override) {
          returns(string)
          body {
            statement("return \"widget\"")
          }
        }
        function("size", public, get) {
          returns(number)
          body {
            statement("return 1")
          }
        }
        function("size", public, set) {
          parameter("value", number)
          body {
            statement("void value")
          }
        }
        function("items") {
          generator()
          returns(TypeName.parameterizedType(TypeName.GENERATOR, number))
          body {
            statement("yield 1")
          }
        }
        // A decorator in parameter position, the third place one can appear.
        function("create", public, static) {
          parameter("engine", engine) { decorator(loggedDecorator) }
          returns(TypeName.implicit("Widget"))
          body {
            statement("return new Widget(engine)")
          }
        }
      }

      // ---- Namespace -----------------------------------------------------------------
      // Namespaces and modules differ only in keyword; ModuleSpec.Kind picks which.
      namespace("Shapes", export) {
        interfaze("Circle") { property("radius", number) }
      }

      // Two parameter properties in one constructor, which is the list Prettier breaks whatever
      // its width -- one on its own, as Widget has, stays inline.
      clazz("Pair", export) {
        property("left", string, private, readonly) { initializer("left") }
        property("right", string, private, readonly) { initializer("right") }
        constructor {
          parameter("left", string)
          parameter("right", string)
          // No body: the parameter properties are the whole constructor, which is the
          // shape this is for and the reason an empty body has to come out as `{}`.
        }
      }

      // `declare`, which says a thing exists without defining it. It is exclusive with `export`
      // on a module, so it needs one of its own rather than a modifier on Shapes.
      namespace("Ambient", declare) {
        interfaze("Host") { property("version", string) }
      }

      // ---- Top-level variables and exports --------------------------------------------
      // A top-level property is a variable declaration, so it must carry exactly one of
      // const, let or VAR -- unlike every other member, where those modifiers are rejected.
      //
      // The four export statements are the forms that are not simply a modifier on a
      // declaration. `export =` is absent on purpose: it cannot coexist with any ES export in
      // one file, which FileSpec enforces, so it cannot appear here at all.
      property("defaultLogger", logger, let)
      property("VERSION", string, const) { initializer("%S", "2.0.0") }

      // `export default` is a modifier rather than a statement, and a file may carry one.
      clazz("Catalogue", export, default) {
        property("entries", TypeName.arrayShorthandType(string), readonly) { initializer("[]") }
      }

      export(ExportSpec.all("./engine"))
      export(ExportSpec.allAs("utilities", "./utils"))
      export(ExportSpec.named(listOf(ExportSpec.name("Options")), from = "./options", typeOnly = true))
      export(ExportSpec.named(listOf(ExportSpec.name("Widget", "Gadget"))))
    }
  }

  fun emit(): String {
    val out = StringWriter()
    spec().writeTo(out)
    return out.toString()
  }
}
