// Generated by TypeScriptPoet. Do not edit.
//
import { logged, sealed } from "./decorators";
import { Engine } from "./engine";
import Logger from "./logger";
import { type Options } from "./options";
import * as utils from "./utils";
import "./polyfill";

/**
 * A person, as described by the source metadata.
 */
export interface Person {
  name: string;

  age?: number;

  readonly id: string;
}

export interface Callable {
  (value: string): number;

  [key: string]: unknown;
}

export interface Identified {
  readonly id: string;
}

type PersonKey = keyof Person;

type PersonName = Person["name"];

type Names = readonly string[];

type Engines = Array<Engine>;

type Registry = Map<string, number>;

type Unique = Set<string>;

type Coordinates = readonly [x: number, y?: number];

type Rest = [string, ...rest: number[]];

type Choice = string | number | null;

type Both = Person & Options;

type Anon = { label: string; hint?: string };

type MixedArray = (string | number)[];

type KeysOfEither = keyof (Person | Options);

type Handler = (event: string) => void;

type Identity = <V>(value: V) => V;

type EngineFactory = new () => Engine;

type AbstractEngineFactory = abstract new () => Engine;

type Bounded<B extends Person> = () => B;

type Producer<out O> = () => O;

type Unwrap<T> = T extends (infer U)[] ? U : never;

type Mutable<T> = { -readonly [K in keyof T]+?: T[K] };

type Getters<T> = {
  [K in keyof T as `get${Capitalize<Extract<K, string>>}`]: T[K];
};

type TypeOfEngine = typeof Engine;

export enum Direction {
  Up = "UP",
  Down = "DOWN",
}

const enum Flags {
  None = 0,
  All = 1 << 2,
}

/**
 * Narrows an unknown value to Person.
 */
export function isPerson(value: unknown): value is Person {
  return typeof value === "object" && value !== null && "name" in value;
}

function assertPerson(value: unknown): asserts value is Person {
  if (!isPerson(value)) throw new Error("not a person");
}

function assertReady(value: unknown): asserts value {
  if (!value) throw new Error("not ready");
}

function pick<const C>(value: C): C {
  return value;
}

function describe(this: Person): string {
  return this.name;
}

async function load(): Promise<string> {
  return "loaded";
}

function* counter(): Generator<number> {
  yield 1;
}

async function* stream(): AsyncGenerator<number> {
  yield 1;
}

function greet(
  greeting: string = "hello",
  name?: string,
  ...extras: string[]
): string {
  return [greeting, name, ...extras].join(" ");
}

function configure({ verbose: loud }: Options): boolean {
  return loud;
}

function swap([first, second]: [string, string]): [string, string] {
  return [second, first];
}

function useUtils(): string {
  return utils.identity("x");
}

function parse(value: string): string;

function parse(value: number): number;

function parse(value: string | number): string | number {
  return value;
}

export function node(path: string) {
  return {
    kind: "node",
    path,
    get depth() {
      return path.split("/").length;
    },
    send: (message: string): void => {
      console.log(message);
    },
  };
}

export abstract class Base<S extends string> {
  greet(): string {
    return "hi";
  }

  protected abstract describe(): string;
}

/**
 * The widget the generator produces.
 */
@sealed
export class Widget extends Base<string> implements Identified {
  #secret: string = "s";

  later!: string;

  accessor count: number = 0;

  static readonly registry: Map<string, number> = new Map();

  onEvent: (event: string) => void = (event: string): void => {
    void event;
  };

  readonly id: string = "widget";

  [key: string]: unknown;

  constructor(private readonly engine: Engine) {
    super();
  }

  static {
    Widget.registry.set("widget", 1);
  }

  @logged
  override greet(): string {
    return this.#secret;
  }

  protected override describe(): string {
    return "widget";
  }

  get size(): number {
    return 1;
  }

  set size(value: number) {
    void value;
  }

  *items(): Generator<number> {
    yield 1;
  }

  static create(engine: Engine): Widget {
    return new Widget(engine);
  }
}

let defaultLogger: Logger;

const VERSION: string = "2.0.0";

export * from "./engine";

export * as utilities from "./utils";

export type { Options } from "./options";

export { Widget as Gadget };

export namespace Shapes {
  interface Circle {
    radius: number;
  }
}

polyfillLoaded;
